version: 2

project_name: terraform-provider-zedamigo

builds:
  - id: terraform-provider-zedamigo
    # main: ./main.go # Default is `.` which includes all .go files in the current dir.
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - GOTOOLCHAIN=local
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags
      - 'osusergo netgo'
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildDate={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}
    targets:
      - linux_amd64
      - darwin_arm64

archives:
  # Standard Terraform-style ZIP archives.
  - id: terraform-archives
    builds:
      - terraform-provider-zedamigo
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  # Raw binaries (one per OS/arch).
  - id: standalone-binaries
    builds:
      - terraform-provider-zedamigo
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: false
  prerelease: auto
  github:
    owner: andrei-zededa 
    name: terraform-provider-zedamigo
  extra_files:
    - glob: ./install.sh
