name: release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags.
  # Manual trigger with specific container image tag.
  workflow_dispatch:
    inputs:
      version:
        description: 'CURRENTLY IGNORED ? - Set the version of the triggered build'
        required: true
        default: 'latest'
        type: string

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: 1.25.1
          cache: true

      - run: go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          version: v2.12.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
