name: release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags.
  # Manual trigger.
  workflow_dispatch:
    inputs:
      version:
        description: 'CURRENTLY IGNORED – manual runs derive version as 0.0.0-branch+commit'
        required: false
        default: ''
        type: string

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: 1.25.1
          cache: true

      - run: go version

      # Only on manual runs: compute 0.0.0-branch+commit and tag HEAD with it.
      - name: Create tag for manual release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          # sanitize branch for semver prerelease (replace slashes/spaces, keep [.A-Za-z0-9-])
          SAFE_BRANCH="$(echo "$BRANCH" | tr '/[:space:]' '-' | tr -cd 'A-Za-z0-9.-_')"
          COMMIT="$(git rev-parse --short HEAD)"
          VERSION="0.0.0-${SAFE_BRANCH}+${COMMIT}"

          echo "Derived VERSION: $VERSION"
          echo "GORELEASER_TAG=$VERSION" >> "$GITHUB_ENV"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # annotate to be explicit; goreleaser will publish the tag/release on GitHub
          git tag -a "$VERSION" -m "Manual release from $BRANCH at $COMMIT"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          version: v2.12.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
